locations:
  - type: git
    location: ~/ttm/*
  - type: git
    location: ~/EF
  - type: git
    location: ~/Reference
  - type: git
    location: ~/Projects/*
  - type: inbox
    location: ~/Desktop
  - type: inbox
    location: ~/Inbox
