---
:issue_count: ~/var/loose-ends/count
:issue_list: ~/var/loose-ends/list
:git_dirs:
  - ~/ttm/apangea
  - ~/ttm/meta
  - ~/Projects/*
  - ~/Reference
  - ~/browser-sessions
  - ~/EF
  - ~/
:inbox_dirs:
  - ~/Inbox
